# NumPy Practice

Working with arrays and simple numerical operations.

In [1]:
import numpy as np

In [2]:
a = np.array([5, 10, 15, 20, 25])
print(a)
print(type(a))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [3]:
print(a[1])
print(a[-1])
print(a[1:4])
print(a.shape)
print(a.ndim)

10
25
[10 15 20]
(5,)
1


In [4]:
b = np.array([2, 4, 6, 8, 10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 7 14 21 28 35]
[ 3  6  9 12 15]
[ 10  40  90 160 250]
[2.5 2.5 2.5 2.5 2.5]


In [5]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))

75
15.0
15.0
5
25


In [6]:
x = np.arange(2, 22, 2)
print(x)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
print(np.zeros(6))
print(np.ones(4))
print(np.linspace(0, 1, 6))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[0.  0.2 0.4 0.6 0.8 1. ]


In [8]:
matrix = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(matrix)
print(matrix.shape)
print(matrix[0])
print(matrix[:, 1])

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
(3, 3)
[2 4 6]
[ 4 10 16]


In [9]:
print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))

[24 30 36]
[12 30 48]


In [10]:
print(np.amin(matrix, axis=0))
print(np.amax(matrix, axis=1))

[2 4 6]
[ 6 12 18]


In [11]:
values = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.where(values % 2 == 0, 'even', 'odd'))

['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']


In [12]:
result = np.select([values < 4, values >= 6], [values * 2, values + 10], default=values)
print(result)

[ 2  4  6  4  5 16 17 18]


In [13]:
marks = np.array([42, 55, 63, 71, 88, 94])
print(np.percentile(marks, 50))
print(np.var(marks))
print(np.std(marks))

67.0
325.13888888888886
18.031608050556358


In [14]:
angles = np.array([0, 30, 60, 90])
r = angles * np.pi / 180
print(np.sin(r))
print(np.cos(r))

[0.        0.5       0.8660254 1.       ]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]


In [15]:
v = np.array([-2.3, 0.7, 4.9, -8.1])
print(np.floor(v))
print(np.ceil(v))

[-3.  0.  4. -9.]
[-2.  1.  5. -8.]


In [16]:
p = np.array([[1, 2], [3, 4]])
q = np.array([[5, 6], [7, 8]])
print(np.dot(p, q))
print(p.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
